name: pick_image
description: A new Flutter project.

publish_to:
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #image picker package
  image_picker: ^0.8.7+1
  firebase_storage: ^11.1.0
  provider: ^6.0.5
  path: ^1.8.2
  firebase_core : ^2.9.0
  firebase_core_web: ^2.3.0
  firebase_core_dart: ^1.0.1
  lottie: ^2.3.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_crashlytics: ^3.1.0
  cloud_firestore: ^4.5.0
  firebase_database: ^10.1.0
  flutter_phoenix: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/images/

